server:
  port: 8083

spring:
  application:    name: GATEWAY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  prefix: /logical
  routes:
    dummyservices:
      path: /url/**
      service-id: EMPLOYEE-SEARCH        
     