spring:
  datasource:
   url: "jdbc:mysql://localhost:3306/employee1"
   username: root
   password: prasath015
   driver-class-name: com.mysql.jdbc.Driver
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
   properties:
    hibernate:
     dialects: org.hibernate.dialect.MySQLDialect
  
